apiVersion: v1
kind: Pod
metadata:
  name: tomcat-container
  labels:
    app: tomcat
spec:
  containers:
  - name: tomcat
    image: kaushal117/dockertest:tomcat
    ports:
    - containerPort: 8080
